/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.6.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QWidget *mainMenu;
    QPushButton *mainMenu_startNewGameButton;
    QLabel *mainMenu_background;
    QPushButton *mainMenu_optionsButton;
    QLabel *mainMenu_logo;
    QPushButton *mainMenu_easterEggButton;
    QLabel *DoctaLiu;
    QWidget *optionsMenu;
    QLabel *optionsMenu_background;
    QPushButton *optionsMenu_changeCardBackDesignButton;
    QLabel *optionsMenu_design;
    QPushButton *optionsMenu_changeBackgroundButton;
    QPushButton *optionsMenu_removeTimerButton;
    QPushButton *optionsMenu_backToMainMenuButton;
    QWidget *gameplay;
    QLabel *gameplay_background;
    QPushButton *gameplay_quitGameButton;
    QLabel *gameplay_timerCount;
    QPushButton *gameplay_timerButtonTemplate;
    QLabel *gameplay_timerLabel;
    QPushButton *card_1H;
    QPushButton *card_11S;
    QPushButton *card_10S;
    QPushButton *card_9S;
    QPushButton *card_13S;
    QPushButton *card_12S;
    QPushButton *card_8S;
    QPushButton *card_7S;
    QPushButton *card_6S;
    QPushButton *card_5S;
    QPushButton *card_4S;
    QPushButton *card_3S;
    QPushButton *card_2S;
    QPushButton *card_1S;
    QPushButton *card_13D;
    QPushButton *card_12D;
    QPushButton *card_11D;
    QPushButton *card_10D;
    QPushButton *card_9D;
    QPushButton *card_8D;
    QPushButton *card_7D;
    QPushButton *card_6D;
    QPushButton *card_5D;
    QPushButton *card_4D;
    QPushButton *card_3D;
    QPushButton *card_2D;
    QPushButton *card_1D;
    QPushButton *card_13C;
    QPushButton *card_12C;
    QPushButton *card_11C;
    QPushButton *card_10C;
    QPushButton *card_9C;
    QPushButton *card_8C;
    QPushButton *card_7C;
    QPushButton *card_6C;
    QPushButton *card_5C;
    QPushButton *card_4C;
    QPushButton *card_3C;
    QPushButton *card_2C;
    QPushButton *card_1C;
    QPushButton *card_13H;
    QPushButton *card_12H;
    QPushButton *card_11H;
    QPushButton *card_10H;
    QPushButton *card_9H;
    QPushButton *card_8H;
    QPushButton *card_7H;
    QPushButton *card_6H;
    QPushButton *card_5H;
    QPushButton *card_4H;
    QPushButton *card_3H;
    QPushButton *card_2H;
    QPushButton *deck;
    QPushButton *tableau_1;
    QPushButton *tableau_2;
    QPushButton *tableau_3;
    QPushButton *tableau_4;
    QPushButton *tableau_5;
    QPushButton *tableau_6;
    QPushButton *tableau_7;
    QPushButton *foundation_heart;
    QPushButton *foundation_spade;
    QPushButton *foundation_diamond;
    QPushButton *foundation_club;
    QLabel *winScreen;
    QWidget *cardBackMenu;
    QLabel *cardBackMenu_background;
    QPushButton *cardBackMenu_returnToOptionsMenuButton;
    QLabel *cardBack_1;
    QLabel *cardBack_2;
    QLabel *cardBack_3;
    QLabel *cardBack_4;
    QLabel *cardBack_5;
    QLabel *cardBack_6;
    QPushButton *setBackFour;
    QPushButton *setBackFive;
    QPushButton *setBackSix;
    QPushButton *setBackOne;
    QPushButton *setBackThree;
    QPushButton *setBackTwo;
    QWidget *backgroundMenu;
    QLabel *backgroundMenu_background;
    QPushButton *backgroundMenu_returnToOptionsMenuButton;
    QLabel *backgroundMenu_backgroundWoodIcon;
    QLabel *backgroundMenu_backgroundStarWarsIcon;
    QLabel *backgroundMenu_backgroundVelvetIcon;
    QLabel *backgroundMenu_backgroundChalkboardIcon;
    QLabel *backgroundMenu_backgroundMemeIcon;
    QLabel *backgroundMenu_backgroundCircuitIcon;
    QPushButton *backgroundMenu_setWoodBackgroundButton;
    QPushButton *backgroundMenu_setVelvetBackgroundButton;
    QPushButton *backgroundMenu_setCircuitBackgroundButton;
    QPushButton *backgroundMenu_setChalkboardBackgroundButton;
    QPushButton *backgroundMenu_setStarWarsBackgroundButton;
    QPushButton *backgroundMenu_setMemeBackgroundButton;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(900, 600);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        mainMenu = new QWidget(centralWidget);
        mainMenu->setObjectName(QStringLiteral("mainMenu"));
        mainMenu->setGeometry(QRect(0, 0, 900, 600));
        mainMenu_startNewGameButton = new QPushButton(mainMenu);
        mainMenu_startNewGameButton->setObjectName(QStringLiteral("mainMenu_startNewGameButton"));
        mainMenu_startNewGameButton->setGeometry(QRect(370, 470, 171, 32));
        mainMenu_background = new QLabel(mainMenu);
        mainMenu_background->setObjectName(QStringLiteral("mainMenu_background"));
        mainMenu_background->setGeometry(QRect(0, 0, 900, 600));
        mainMenu_background->setPixmap(QPixmap(QString::fromUtf8("Backgrounds/defaultBackground.jpg")));
        mainMenu_optionsButton = new QPushButton(mainMenu);
        mainMenu_optionsButton->setObjectName(QStringLiteral("mainMenu_optionsButton"));
        mainMenu_optionsButton->setGeometry(QRect(400, 510, 113, 32));
        mainMenu_logo = new QLabel(mainMenu);
        mainMenu_logo->setObjectName(QStringLiteral("mainMenu_logo"));
        mainMenu_logo->setGeometry(QRect(-10, 50, 861, 521));
        mainMenu_logo->setPixmap(QPixmap(QString::fromUtf8("SoLITaire Logo.png")));
        mainMenu_easterEggButton = new QPushButton(mainMenu);
        mainMenu_easterEggButton->setObjectName(QStringLiteral("mainMenu_easterEggButton"));
        mainMenu_easterEggButton->setGeometry(QRect(610, 280, 31, 31));
        DoctaLiu = new QLabel(mainMenu);
        DoctaLiu->setObjectName(QStringLiteral("DoctaLiu"));
        DoctaLiu->setGeometry(QRect(150, 90, 81, 121));
        DoctaLiu->setPixmap(QPixmap(QString::fromUtf8("DoctaLiu.jpeg")));
        mainMenu_background->raise();
        mainMenu_logo->raise();
        mainMenu_startNewGameButton->raise();
        mainMenu_optionsButton->raise();
        mainMenu_easterEggButton->raise();
        DoctaLiu->raise();
        optionsMenu = new QWidget(centralWidget);
        optionsMenu->setObjectName(QStringLiteral("optionsMenu"));
        optionsMenu->setGeometry(QRect(0, 0, 900, 600));
        optionsMenu->setToolTipDuration(53);
        optionsMenu_background = new QLabel(optionsMenu);
        optionsMenu_background->setObjectName(QStringLiteral("optionsMenu_background"));
        optionsMenu_background->setGeometry(QRect(0, 0, 900, 600));
        optionsMenu_background->setPixmap(QPixmap(QString::fromUtf8("Backgrounds/defaultBackground.jpg")));
        optionsMenu_changeCardBackDesignButton = new QPushButton(optionsMenu);
        optionsMenu_changeCardBackDesignButton->setObjectName(QStringLiteral("optionsMenu_changeCardBackDesignButton"));
        optionsMenu_changeCardBackDesignButton->setGeometry(QRect(100, 90, 270, 30));
        optionsMenu_design = new QLabel(optionsMenu);
        optionsMenu_design->setObjectName(QStringLiteral("optionsMenu_design"));
        optionsMenu_design->setGeometry(QRect(0, 380, 801, 561));
        optionsMenu_design->setPixmap(QPixmap(QString::fromUtf8("SoLITaire Logo.png")));
        optionsMenu_changeBackgroundButton = new QPushButton(optionsMenu);
        optionsMenu_changeBackgroundButton->setObjectName(QStringLiteral("optionsMenu_changeBackgroundButton"));
        optionsMenu_changeBackgroundButton->setGeometry(QRect(530, 90, 270, 30));
        optionsMenu_removeTimerButton = new QPushButton(optionsMenu);
        optionsMenu_removeTimerButton->setObjectName(QStringLiteral("optionsMenu_removeTimerButton"));
        optionsMenu_removeTimerButton->setGeometry(QRect(320, 220, 270, 30));
        optionsMenu_backToMainMenuButton = new QPushButton(optionsMenu);
        optionsMenu_backToMainMenuButton->setObjectName(QStringLiteral("optionsMenu_backToMainMenuButton"));
        optionsMenu_backToMainMenuButton->setGeometry(QRect(320, 330, 270, 30));
        gameplay = new QWidget(centralWidget);
        gameplay->setObjectName(QStringLiteral("gameplay"));
        gameplay->setGeometry(QRect(0, 0, 900, 600));
        gameplay_background = new QLabel(gameplay);
        gameplay_background->setObjectName(QStringLiteral("gameplay_background"));
        gameplay_background->setGeometry(QRect(0, 0, 900, 600));
        gameplay_background->setPixmap(QPixmap(QString::fromUtf8("Backgrounds/defaultBackground.jpg")));
        gameplay_quitGameButton = new QPushButton(gameplay);
        gameplay_quitGameButton->setObjectName(QStringLiteral("gameplay_quitGameButton"));
        gameplay_quitGameButton->setGeometry(QRect(20, 550, 161, 32));
        gameplay_timerCount = new QLabel(gameplay);
        gameplay_timerCount->setObjectName(QStringLiteral("gameplay_timerCount"));
        gameplay_timerCount->setGeometry(QRect(820, 539, 31, 51));
        QFont font;
        font.setPointSize(12);
        gameplay_timerCount->setFont(font);
        gameplay_timerButtonTemplate = new QPushButton(gameplay);
        gameplay_timerButtonTemplate->setObjectName(QStringLiteral("gameplay_timerButtonTemplate"));
        gameplay_timerButtonTemplate->setGeometry(QRect(710, 550, 161, 30));
        QFont font1;
        font1.setKerning(true);
        font1.setStyleStrategy(QFont::PreferDefault);
        gameplay_timerButtonTemplate->setFont(font1);
        gameplay_timerButtonTemplate->setFocusPolicy(Qt::NoFocus);
        gameplay_timerButtonTemplate->setText(QStringLiteral(""));
        gameplay_timerLabel = new QLabel(gameplay);
        gameplay_timerLabel->setObjectName(QStringLiteral("gameplay_timerLabel"));
        gameplay_timerLabel->setGeometry(QRect(740, 556, 59, 16));
        card_1H = new QPushButton(gameplay);
        card_1H->setObjectName(QStringLiteral("card_1H"));
        card_1H->setGeometry(QRect(760, 40, 73, 97));
        card_11S = new QPushButton(gameplay);
        card_11S->setObjectName(QStringLiteral("card_11S"));
        card_11S->setGeometry(QRect(760, 40, 73, 97));
        card_10S = new QPushButton(gameplay);
        card_10S->setObjectName(QStringLiteral("card_10S"));
        card_10S->setGeometry(QRect(760, 40, 73, 97));
        card_9S = new QPushButton(gameplay);
        card_9S->setObjectName(QStringLiteral("card_9S"));
        card_9S->setGeometry(QRect(760, 40, 73, 97));
        card_13S = new QPushButton(gameplay);
        card_13S->setObjectName(QStringLiteral("card_13S"));
        card_13S->setGeometry(QRect(760, 40, 73, 97));
        card_12S = new QPushButton(gameplay);
        card_12S->setObjectName(QStringLiteral("card_12S"));
        card_12S->setGeometry(QRect(760, 40, 73, 97));
        card_8S = new QPushButton(gameplay);
        card_8S->setObjectName(QStringLiteral("card_8S"));
        card_8S->setGeometry(QRect(760, 40, 73, 97));
        card_7S = new QPushButton(gameplay);
        card_7S->setObjectName(QStringLiteral("card_7S"));
        card_7S->setGeometry(QRect(760, 40, 73, 97));
        card_6S = new QPushButton(gameplay);
        card_6S->setObjectName(QStringLiteral("card_6S"));
        card_6S->setGeometry(QRect(760, 40, 73, 97));
        card_5S = new QPushButton(gameplay);
        card_5S->setObjectName(QStringLiteral("card_5S"));
        card_5S->setGeometry(QRect(760, 40, 73, 97));
        card_4S = new QPushButton(gameplay);
        card_4S->setObjectName(QStringLiteral("card_4S"));
        card_4S->setGeometry(QRect(760, 40, 73, 97));
        card_3S = new QPushButton(gameplay);
        card_3S->setObjectName(QStringLiteral("card_3S"));
        card_3S->setGeometry(QRect(760, 40, 73, 97));
        card_2S = new QPushButton(gameplay);
        card_2S->setObjectName(QStringLiteral("card_2S"));
        card_2S->setGeometry(QRect(760, 40, 73, 97));
        card_1S = new QPushButton(gameplay);
        card_1S->setObjectName(QStringLiteral("card_1S"));
        card_1S->setGeometry(QRect(760, 40, 73, 97));
        card_13D = new QPushButton(gameplay);
        card_13D->setObjectName(QStringLiteral("card_13D"));
        card_13D->setGeometry(QRect(760, 40, 73, 97));
        card_12D = new QPushButton(gameplay);
        card_12D->setObjectName(QStringLiteral("card_12D"));
        card_12D->setGeometry(QRect(760, 40, 73, 97));
        card_11D = new QPushButton(gameplay);
        card_11D->setObjectName(QStringLiteral("card_11D"));
        card_11D->setGeometry(QRect(760, 40, 73, 97));
        card_10D = new QPushButton(gameplay);
        card_10D->setObjectName(QStringLiteral("card_10D"));
        card_10D->setGeometry(QRect(760, 40, 73, 97));
        card_9D = new QPushButton(gameplay);
        card_9D->setObjectName(QStringLiteral("card_9D"));
        card_9D->setGeometry(QRect(760, 40, 73, 97));
        card_8D = new QPushButton(gameplay);
        card_8D->setObjectName(QStringLiteral("card_8D"));
        card_8D->setGeometry(QRect(760, 40, 73, 97));
        card_7D = new QPushButton(gameplay);
        card_7D->setObjectName(QStringLiteral("card_7D"));
        card_7D->setGeometry(QRect(760, 40, 73, 97));
        card_6D = new QPushButton(gameplay);
        card_6D->setObjectName(QStringLiteral("card_6D"));
        card_6D->setGeometry(QRect(760, 40, 73, 97));
        card_5D = new QPushButton(gameplay);
        card_5D->setObjectName(QStringLiteral("card_5D"));
        card_5D->setGeometry(QRect(760, 40, 73, 97));
        card_4D = new QPushButton(gameplay);
        card_4D->setObjectName(QStringLiteral("card_4D"));
        card_4D->setGeometry(QRect(760, 40, 73, 97));
        card_3D = new QPushButton(gameplay);
        card_3D->setObjectName(QStringLiteral("card_3D"));
        card_3D->setGeometry(QRect(760, 40, 73, 97));
        card_2D = new QPushButton(gameplay);
        card_2D->setObjectName(QStringLiteral("card_2D"));
        card_2D->setGeometry(QRect(760, 40, 73, 97));
        card_1D = new QPushButton(gameplay);
        card_1D->setObjectName(QStringLiteral("card_1D"));
        card_1D->setGeometry(QRect(760, 40, 73, 97));
        card_13C = new QPushButton(gameplay);
        card_13C->setObjectName(QStringLiteral("card_13C"));
        card_13C->setGeometry(QRect(760, 40, 73, 97));
        card_12C = new QPushButton(gameplay);
        card_12C->setObjectName(QStringLiteral("card_12C"));
        card_12C->setGeometry(QRect(760, 40, 73, 97));
        card_11C = new QPushButton(gameplay);
        card_11C->setObjectName(QStringLiteral("card_11C"));
        card_11C->setGeometry(QRect(760, 40, 73, 97));
        card_10C = new QPushButton(gameplay);
        card_10C->setObjectName(QStringLiteral("card_10C"));
        card_10C->setGeometry(QRect(760, 40, 73, 97));
        card_9C = new QPushButton(gameplay);
        card_9C->setObjectName(QStringLiteral("card_9C"));
        card_9C->setGeometry(QRect(760, 40, 73, 97));
        card_8C = new QPushButton(gameplay);
        card_8C->setObjectName(QStringLiteral("card_8C"));
        card_8C->setGeometry(QRect(760, 40, 73, 97));
        card_7C = new QPushButton(gameplay);
        card_7C->setObjectName(QStringLiteral("card_7C"));
        card_7C->setGeometry(QRect(760, 40, 73, 97));
        card_6C = new QPushButton(gameplay);
        card_6C->setObjectName(QStringLiteral("card_6C"));
        card_6C->setGeometry(QRect(760, 40, 73, 97));
        card_5C = new QPushButton(gameplay);
        card_5C->setObjectName(QStringLiteral("card_5C"));
        card_5C->setGeometry(QRect(760, 40, 73, 97));
        card_4C = new QPushButton(gameplay);
        card_4C->setObjectName(QStringLiteral("card_4C"));
        card_4C->setGeometry(QRect(760, 40, 73, 97));
        card_3C = new QPushButton(gameplay);
        card_3C->setObjectName(QStringLiteral("card_3C"));
        card_3C->setGeometry(QRect(760, 40, 73, 97));
        card_2C = new QPushButton(gameplay);
        card_2C->setObjectName(QStringLiteral("card_2C"));
        card_2C->setGeometry(QRect(760, 40, 73, 97));
        card_1C = new QPushButton(gameplay);
        card_1C->setObjectName(QStringLiteral("card_1C"));
        card_1C->setGeometry(QRect(760, 40, 73, 97));
        card_13H = new QPushButton(gameplay);
        card_13H->setObjectName(QStringLiteral("card_13H"));
        card_13H->setGeometry(QRect(760, 40, 73, 97));
        card_12H = new QPushButton(gameplay);
        card_12H->setObjectName(QStringLiteral("card_12H"));
        card_12H->setGeometry(QRect(760, 40, 73, 97));
        card_11H = new QPushButton(gameplay);
        card_11H->setObjectName(QStringLiteral("card_11H"));
        card_11H->setGeometry(QRect(760, 40, 73, 97));
        card_10H = new QPushButton(gameplay);
        card_10H->setObjectName(QStringLiteral("card_10H"));
        card_10H->setGeometry(QRect(760, 40, 73, 97));
        card_9H = new QPushButton(gameplay);
        card_9H->setObjectName(QStringLiteral("card_9H"));
        card_9H->setGeometry(QRect(760, 40, 73, 97));
        card_8H = new QPushButton(gameplay);
        card_8H->setObjectName(QStringLiteral("card_8H"));
        card_8H->setGeometry(QRect(760, 40, 73, 97));
        card_7H = new QPushButton(gameplay);
        card_7H->setObjectName(QStringLiteral("card_7H"));
        card_7H->setGeometry(QRect(760, 40, 73, 97));
        card_6H = new QPushButton(gameplay);
        card_6H->setObjectName(QStringLiteral("card_6H"));
        card_6H->setGeometry(QRect(760, 40, 73, 97));
        card_5H = new QPushButton(gameplay);
        card_5H->setObjectName(QStringLiteral("card_5H"));
        card_5H->setGeometry(QRect(760, 40, 73, 97));
        card_4H = new QPushButton(gameplay);
        card_4H->setObjectName(QStringLiteral("card_4H"));
        card_4H->setGeometry(QRect(760, 40, 73, 97));
        card_3H = new QPushButton(gameplay);
        card_3H->setObjectName(QStringLiteral("card_3H"));
        card_3H->setGeometry(QRect(760, 40, 73, 97));
        card_2H = new QPushButton(gameplay);
        card_2H->setObjectName(QStringLiteral("card_2H"));
        card_2H->setGeometry(QRect(760, 40, 73, 97));
        deck = new QPushButton(gameplay);
        deck->setObjectName(QStringLiteral("deck"));
        deck->setGeometry(QRect(760, 42, 74, 97));
        tableau_1 = new QPushButton(gameplay);
        tableau_1->setObjectName(QStringLiteral("tableau_1"));
        tableau_1->setGeometry(QRect(20, 190, 73, 97));
        tableau_2 = new QPushButton(gameplay);
        tableau_2->setObjectName(QStringLiteral("tableau_2"));
        tableau_2->setGeometry(QRect(150, 190, 73, 97));
        tableau_3 = new QPushButton(gameplay);
        tableau_3->setObjectName(QStringLiteral("tableau_3"));
        tableau_3->setGeometry(QRect(280, 190, 73, 97));
        tableau_4 = new QPushButton(gameplay);
        tableau_4->setObjectName(QStringLiteral("tableau_4"));
        tableau_4->setGeometry(QRect(410, 190, 73, 97));
        tableau_5 = new QPushButton(gameplay);
        tableau_5->setObjectName(QStringLiteral("tableau_5"));
        tableau_5->setGeometry(QRect(540, 190, 73, 97));
        tableau_6 = new QPushButton(gameplay);
        tableau_6->setObjectName(QStringLiteral("tableau_6"));
        tableau_6->setGeometry(QRect(670, 190, 73, 97));
        tableau_7 = new QPushButton(gameplay);
        tableau_7->setObjectName(QStringLiteral("tableau_7"));
        tableau_7->setGeometry(QRect(800, 190, 73, 97));
        foundation_heart = new QPushButton(gameplay);
        foundation_heart->setObjectName(QStringLiteral("foundation_heart"));
        foundation_heart->setGeometry(QRect(60, 40, 73, 97));
        foundation_spade = new QPushButton(gameplay);
        foundation_spade->setObjectName(QStringLiteral("foundation_spade"));
        foundation_spade->setGeometry(QRect(180, 40, 73, 97));
        foundation_diamond = new QPushButton(gameplay);
        foundation_diamond->setObjectName(QStringLiteral("foundation_diamond"));
        foundation_diamond->setGeometry(QRect(300, 40, 73, 97));
        foundation_club = new QPushButton(gameplay);
        foundation_club->setObjectName(QStringLiteral("foundation_club"));
        foundation_club->setGeometry(QRect(420, 40, 73, 97));
        winScreen = new QLabel(gameplay);
        winScreen->setObjectName(QStringLiteral("winScreen"));
        winScreen->setGeometry(QRect(0, 0, 900, 600));
        winScreen->raise();
        gameplay_background->raise();
        gameplay_quitGameButton->raise();
        gameplay_timerButtonTemplate->raise();
        gameplay_timerCount->raise();
        gameplay_timerLabel->raise();
        card_8S->raise();
        card_7H->raise();
        card_2C->raise();
        card_10S->raise();
        card_6C->raise();
        card_13D->raise();
        card_7D->raise();
        card_4H->raise();
        card_8C->raise();
        card_2D->raise();
        card_5H->raise();
        card_5C->raise();
        card_3H->raise();
        card_8D->raise();
        card_11H->raise();
        card_1S->raise();
        card_13S->raise();
        card_13H->raise();
        card_9H->raise();
        card_9S->raise();
        card_7C->raise();
        card_3D->raise();
        card_9C->raise();
        card_8H->raise();
        card_4C->raise();
        card_7S->raise();
        card_10H->raise();
        card_13C->raise();
        card_10C->raise();
        card_6S->raise();
        card_12C->raise();
        card_11D->raise();
        card_11C->raise();
        card_12H->raise();
        card_5D->raise();
        card_1D->raise();
        card_6H->raise();
        card_1H->raise();
        card_2S->raise();
        card_11S->raise();
        card_6D->raise();
        card_4S->raise();
        card_3S->raise();
        card_9D->raise();
        card_12S->raise();
        card_2H->raise();
        card_10D->raise();
        card_12D->raise();
        card_1C->raise();
        card_3C->raise();
        card_5S->raise();
        card_4D->raise();
        deck->raise();
        tableau_1->raise();
        tableau_2->raise();
        tableau_3->raise();
        tableau_4->raise();
        tableau_5->raise();
        tableau_6->raise();
        tableau_7->raise();
        foundation_heart->raise();
        foundation_spade->raise();
        foundation_diamond->raise();
        foundation_club->raise();
        cardBackMenu = new QWidget(centralWidget);
        cardBackMenu->setObjectName(QStringLiteral("cardBackMenu"));
        cardBackMenu->setGeometry(QRect(0, 0, 900, 600));
        cardBackMenu_background = new QLabel(cardBackMenu);
        cardBackMenu_background->setObjectName(QStringLiteral("cardBackMenu_background"));
        cardBackMenu_background->setGeometry(QRect(0, 0, 900, 600));
        cardBackMenu_background->setPixmap(QPixmap(QString::fromUtf8("Backgrounds/defaultBackground.jpg")));
        cardBackMenu_returnToOptionsMenuButton = new QPushButton(cardBackMenu);
        cardBackMenu_returnToOptionsMenuButton->setObjectName(QStringLiteral("cardBackMenu_returnToOptionsMenuButton"));
        cardBackMenu_returnToOptionsMenuButton->setGeometry(QRect(310, 480, 270, 30));
        cardBack_1 = new QLabel(cardBackMenu);
        cardBack_1->setObjectName(QStringLiteral("cardBack_1"));
        cardBack_1->setGeometry(QRect(150, 70, 73, 97));
        cardBack_2 = new QLabel(cardBackMenu);
        cardBack_2->setObjectName(QStringLiteral("cardBack_2"));
        cardBack_2->setGeometry(QRect(410, 70, 73, 97));
        cardBack_3 = new QLabel(cardBackMenu);
        cardBack_3->setObjectName(QStringLiteral("cardBack_3"));
        cardBack_3->setGeometry(QRect(670, 70, 73, 97));
        cardBack_4 = new QLabel(cardBackMenu);
        cardBack_4->setObjectName(QStringLiteral("cardBack_4"));
        cardBack_4->setGeometry(QRect(150, 280, 73, 97));
        cardBack_5 = new QLabel(cardBackMenu);
        cardBack_5->setObjectName(QStringLiteral("cardBack_5"));
        cardBack_5->setGeometry(QRect(410, 280, 73, 97));
        cardBack_6 = new QLabel(cardBackMenu);
        cardBack_6->setObjectName(QStringLiteral("cardBack_6"));
        cardBack_6->setGeometry(QRect(670, 280, 73, 97));
        setBackFour = new QPushButton(cardBackMenu);
        setBackFour->setObjectName(QStringLiteral("setBackFour"));
        setBackFour->setGeometry(QRect(130, 420, 112, 34));
        setBackFive = new QPushButton(cardBackMenu);
        setBackFive->setObjectName(QStringLiteral("setBackFive"));
        setBackFive->setGeometry(QRect(390, 420, 112, 34));
        setBackSix = new QPushButton(cardBackMenu);
        setBackSix->setObjectName(QStringLiteral("setBackSix"));
        setBackSix->setGeometry(QRect(650, 420, 112, 34));
        setBackOne = new QPushButton(cardBackMenu);
        setBackOne->setObjectName(QStringLiteral("setBackOne"));
        setBackOne->setGeometry(QRect(130, 210, 112, 34));
        setBackThree = new QPushButton(cardBackMenu);
        setBackThree->setObjectName(QStringLiteral("setBackThree"));
        setBackThree->setGeometry(QRect(650, 210, 112, 34));
        setBackTwo = new QPushButton(cardBackMenu);
        setBackTwo->setObjectName(QStringLiteral("setBackTwo"));
        setBackTwo->setGeometry(QRect(390, 210, 112, 34));
        backgroundMenu = new QWidget(centralWidget);
        backgroundMenu->setObjectName(QStringLiteral("backgroundMenu"));
        backgroundMenu->setGeometry(QRect(0, 0, 900, 600));
        backgroundMenu_background = new QLabel(backgroundMenu);
        backgroundMenu_background->setObjectName(QStringLiteral("backgroundMenu_background"));
        backgroundMenu_background->setGeometry(QRect(0, 0, 900, 600));
        backgroundMenu_background->setPixmap(QPixmap(QString::fromUtf8("Backgrounds/defaultBackground.jpg")));
        backgroundMenu_returnToOptionsMenuButton = new QPushButton(backgroundMenu);
        backgroundMenu_returnToOptionsMenuButton->setObjectName(QStringLiteral("backgroundMenu_returnToOptionsMenuButton"));
        backgroundMenu_returnToOptionsMenuButton->setGeometry(QRect(310, 480, 270, 30));
        backgroundMenu_backgroundWoodIcon = new QLabel(backgroundMenu);
        backgroundMenu_backgroundWoodIcon->setObjectName(QStringLiteral("backgroundMenu_backgroundWoodIcon"));
        backgroundMenu_backgroundWoodIcon->setGeometry(QRect(90, 70, 150, 100));
        backgroundMenu_backgroundWoodIcon->setPixmap(QPixmap(QString::fromUtf8("Backgrounds/backgroundWoodPlanksIcon.jpg")));
        backgroundMenu_backgroundStarWarsIcon = new QLabel(backgroundMenu);
        backgroundMenu_backgroundStarWarsIcon->setObjectName(QStringLiteral("backgroundMenu_backgroundStarWarsIcon"));
        backgroundMenu_backgroundStarWarsIcon->setGeometry(QRect(370, 270, 150, 100));
        backgroundMenu_backgroundStarWarsIcon->setPixmap(QPixmap(QString::fromUtf8("Backgrounds/backgroundStarWarsIcon.jpg")));
        backgroundMenu_backgroundVelvetIcon = new QLabel(backgroundMenu);
        backgroundMenu_backgroundVelvetIcon->setObjectName(QStringLiteral("backgroundMenu_backgroundVelvetIcon"));
        backgroundMenu_backgroundVelvetIcon->setGeometry(QRect(370, 70, 150, 100));
        backgroundMenu_backgroundVelvetIcon->setPixmap(QPixmap(QString::fromUtf8("Backgrounds/backgroundVelvetIcon.jpg")));
        backgroundMenu_backgroundChalkboardIcon = new QLabel(backgroundMenu);
        backgroundMenu_backgroundChalkboardIcon->setObjectName(QStringLiteral("backgroundMenu_backgroundChalkboardIcon"));
        backgroundMenu_backgroundChalkboardIcon->setGeometry(QRect(90, 270, 150, 100));
        backgroundMenu_backgroundChalkboardIcon->setPixmap(QPixmap(QString::fromUtf8("Backgrounds/backgroundChalkboardIcon.jpg")));
        backgroundMenu_backgroundMemeIcon = new QLabel(backgroundMenu);
        backgroundMenu_backgroundMemeIcon->setObjectName(QStringLiteral("backgroundMenu_backgroundMemeIcon"));
        backgroundMenu_backgroundMemeIcon->setGeometry(QRect(650, 270, 150, 100));
        backgroundMenu_backgroundMemeIcon->setPixmap(QPixmap(QString::fromUtf8("Backgrounds/backgroundMemeIcon.jpg")));
        backgroundMenu_backgroundCircuitIcon = new QLabel(backgroundMenu);
        backgroundMenu_backgroundCircuitIcon->setObjectName(QStringLiteral("backgroundMenu_backgroundCircuitIcon"));
        backgroundMenu_backgroundCircuitIcon->setGeometry(QRect(650, 70, 150, 100));
        backgroundMenu_backgroundCircuitIcon->setPixmap(QPixmap(QString::fromUtf8("Backgrounds/backgroundCircuitBoardIcon.jpg")));
        backgroundMenu_setWoodBackgroundButton = new QPushButton(backgroundMenu);
        backgroundMenu_setWoodBackgroundButton->setObjectName(QStringLiteral("backgroundMenu_setWoodBackgroundButton"));
        backgroundMenu_setWoodBackgroundButton->setGeometry(QRect(60, 180, 210, 30));
        backgroundMenu_setVelvetBackgroundButton = new QPushButton(backgroundMenu);
        backgroundMenu_setVelvetBackgroundButton->setObjectName(QStringLiteral("backgroundMenu_setVelvetBackgroundButton"));
        backgroundMenu_setVelvetBackgroundButton->setGeometry(QRect(340, 180, 210, 30));
        backgroundMenu_setCircuitBackgroundButton = new QPushButton(backgroundMenu);
        backgroundMenu_setCircuitBackgroundButton->setObjectName(QStringLiteral("backgroundMenu_setCircuitBackgroundButton"));
        backgroundMenu_setCircuitBackgroundButton->setGeometry(QRect(620, 180, 210, 30));
        backgroundMenu_setChalkboardBackgroundButton = new QPushButton(backgroundMenu);
        backgroundMenu_setChalkboardBackgroundButton->setObjectName(QStringLiteral("backgroundMenu_setChalkboardBackgroundButton"));
        backgroundMenu_setChalkboardBackgroundButton->setGeometry(QRect(60, 380, 210, 30));
        backgroundMenu_setStarWarsBackgroundButton = new QPushButton(backgroundMenu);
        backgroundMenu_setStarWarsBackgroundButton->setObjectName(QStringLiteral("backgroundMenu_setStarWarsBackgroundButton"));
        backgroundMenu_setStarWarsBackgroundButton->setGeometry(QRect(340, 380, 210, 30));
        backgroundMenu_setMemeBackgroundButton = new QPushButton(backgroundMenu);
        backgroundMenu_setMemeBackgroundButton->setObjectName(QStringLiteral("backgroundMenu_setMemeBackgroundButton"));
        backgroundMenu_setMemeBackgroundButton->setGeometry(QRect(620, 380, 210, 30));
        backgroundMenu_background->raise();
        backgroundMenu_returnToOptionsMenuButton->raise();
        backgroundMenu_backgroundStarWarsIcon->raise();
        backgroundMenu_backgroundVelvetIcon->raise();
        backgroundMenu_backgroundChalkboardIcon->raise();
        backgroundMenu_backgroundMemeIcon->raise();
        backgroundMenu_backgroundCircuitIcon->raise();
        backgroundMenu_setWoodBackgroundButton->raise();
        backgroundMenu_setVelvetBackgroundButton->raise();
        backgroundMenu_setCircuitBackgroundButton->raise();
        backgroundMenu_setChalkboardBackgroundButton->raise();
        backgroundMenu_setStarWarsBackgroundButton->raise();
        backgroundMenu_setMemeBackgroundButton->raise();
        backgroundMenu_backgroundWoodIcon->raise();
        MainWindow->setCentralWidget(centralWidget);
        optionsMenu->raise();
        mainMenu->raise();
        gameplay->raise();
        cardBackMenu->raise();
        backgroundMenu->raise();

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        mainMenu_startNewGameButton->setText(QApplication::translate("MainWindow", "Start New Game", 0));
        mainMenu_background->setText(QString());
        mainMenu_optionsButton->setText(QApplication::translate("MainWindow", "Options", 0));
        mainMenu_logo->setText(QString());
        mainMenu_easterEggButton->setText(QString());
        DoctaLiu->setText(QString());
        optionsMenu_background->setText(QString());
        optionsMenu_changeCardBackDesignButton->setText(QApplication::translate("MainWindow", "Change Card Back Design", 0));
        optionsMenu_design->setText(QString());
        optionsMenu_changeBackgroundButton->setText(QApplication::translate("MainWindow", "Change Background", 0));
        optionsMenu_removeTimerButton->setText(QApplication::translate("MainWindow", "Remove Timer", 0));
        optionsMenu_backToMainMenuButton->setText(QApplication::translate("MainWindow", "Back to Main Menu", 0));
        gameplay_background->setText(QString());
        gameplay_quitGameButton->setText(QApplication::translate("MainWindow", "Quit Game", 0));
        gameplay_timerCount->setText(QApplication::translate("MainWindow", "0", 0));
        gameplay_timerLabel->setText(QApplication::translate("MainWindow", "Timer", 0));
        card_1H->setText(QString());
        card_11S->setText(QString());
        card_10S->setText(QString());
        card_9S->setText(QString());
        card_13S->setText(QString());
        card_12S->setText(QString());
        card_8S->setText(QString());
        card_7S->setText(QString());
        card_6S->setText(QString());
        card_5S->setText(QString());
        card_4S->setText(QString());
        card_3S->setText(QString());
        card_2S->setText(QString());
        card_1S->setText(QString());
        card_13D->setText(QString());
        card_12D->setText(QString());
        card_11D->setText(QString());
        card_10D->setText(QString());
        card_9D->setText(QString());
        card_8D->setText(QString());
        card_7D->setText(QString());
        card_6D->setText(QString());
        card_5D->setText(QString());
        card_4D->setText(QString());
        card_3D->setText(QString());
        card_2D->setText(QString());
        card_1D->setText(QString());
        card_13C->setText(QString());
        card_12C->setText(QString());
        card_11C->setText(QString());
        card_10C->setText(QString());
        card_9C->setText(QString());
        card_8C->setText(QString());
        card_7C->setText(QString());
        card_6C->setText(QString());
        card_5C->setText(QString());
        card_4C->setText(QString());
        card_3C->setText(QString());
        card_2C->setText(QString());
        card_1C->setText(QString());
        card_13H->setText(QString());
        card_12H->setText(QString());
        card_11H->setText(QString());
        card_10H->setText(QString());
        card_9H->setText(QString());
        card_8H->setText(QString());
        card_7H->setText(QString());
        card_6H->setText(QString());
        card_5H->setText(QString());
        card_4H->setText(QString());
        card_3H->setText(QString());
        card_2H->setText(QString());
        deck->setText(QString());
        tableau_1->setText(QString());
        tableau_2->setText(QString());
        tableau_3->setText(QString());
        tableau_4->setText(QString());
        tableau_5->setText(QString());
        tableau_6->setText(QString());
        tableau_7->setText(QString());
        foundation_heart->setText(QString());
        foundation_spade->setText(QString());
        foundation_diamond->setText(QString());
        foundation_club->setText(QString());
        winScreen->setText(QString());
        cardBackMenu_background->setText(QString());
        cardBackMenu_returnToOptionsMenuButton->setText(QApplication::translate("MainWindow", "Return to Options Menu", 0));
        cardBack_1->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        cardBack_2->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        cardBack_3->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        cardBack_4->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        cardBack_5->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        cardBack_6->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        setBackFour->setText(QApplication::translate("MainWindow", "Set Back", 0));
        setBackFive->setText(QApplication::translate("MainWindow", "Set Back", 0));
        setBackSix->setText(QApplication::translate("MainWindow", "Set Back", 0));
        setBackOne->setText(QApplication::translate("MainWindow", "Set Back", 0));
        setBackThree->setText(QApplication::translate("MainWindow", "Set Back", 0));
        setBackTwo->setText(QApplication::translate("MainWindow", "Set Back", 0));
        backgroundMenu_background->setText(QString());
        backgroundMenu_returnToOptionsMenuButton->setText(QApplication::translate("MainWindow", "Return to Options Menu", 0));
        backgroundMenu_backgroundWoodIcon->setText(QString());
        backgroundMenu_backgroundStarWarsIcon->setText(QString());
        backgroundMenu_backgroundVelvetIcon->setText(QString());
        backgroundMenu_backgroundChalkboardIcon->setText(QString());
        backgroundMenu_backgroundMemeIcon->setText(QString());
        backgroundMenu_backgroundCircuitIcon->setText(QString());
        backgroundMenu_setWoodBackgroundButton->setText(QApplication::translate("MainWindow", "Set Wood Background", 0));
        backgroundMenu_setVelvetBackgroundButton->setText(QApplication::translate("MainWindow", "Set Velvet Background", 0));
        backgroundMenu_setCircuitBackgroundButton->setText(QApplication::translate("MainWindow", "Set Circuit Background", 0));
        backgroundMenu_setChalkboardBackgroundButton->setText(QApplication::translate("MainWindow", "Set Chalkboard Background", 0));
        backgroundMenu_setStarWarsBackgroundButton->setText(QApplication::translate("MainWindow", "Set Star Wars Background", 0));
        backgroundMenu_setMemeBackgroundButton->setText(QApplication::translate("MainWindow", "Set Meme Background", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
